# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/hse/file-integrity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/hse/file-integrity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/hse/file-integrity/CMakeFiles /root/hse/file-integrity/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/hse/file-integrity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named daemon

# Build rule for target.
daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon
.PHONY : daemon

# fast build rule for target.
daemon/fast:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/build
.PHONY : daemon/fast

#=============================================================================
# Target rules for targets named fi-client

# Build rule for target.
fi-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fi-client
.PHONY : fi-client

# fast build rule for target.
fi-client/fast:
	$(MAKE) -f CMakeFiles/fi-client.dir/build.make CMakeFiles/fi-client.dir/build
.PHONY : fi-client/fast

#=============================================================================
# Target rules for targets named fi-server

# Build rule for target.
fi-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fi-server
.PHONY : fi-server

# fast build rule for target.
fi-server/fast:
	$(MAKE) -f CMakeFiles/fi-server.dir/build.make CMakeFiles/fi-server.dir/build
.PHONY : fi-server/fast

#=============================================================================
# Target rules for targets named lib_client

# Build rule for target.
lib_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_client
.PHONY : lib_client

# fast build rule for target.
lib_client/fast:
	$(MAKE) -f CMakeFiles/lib_client.dir/build.make CMakeFiles/lib_client.dir/build
.PHONY : lib_client/fast

#=============================================================================
# Target rules for targets named lib_daemon

# Build rule for target.
lib_daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_daemon
.PHONY : lib_daemon

# fast build rule for target.
lib_daemon/fast:
	$(MAKE) -f CMakeFiles/lib_daemon.dir/build.make CMakeFiles/lib_daemon.dir/build
.PHONY : lib_daemon/fast

#=============================================================================
# Target rules for targets named lib_db

# Build rule for target.
lib_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_db
.PHONY : lib_db

# fast build rule for target.
lib_db/fast:
	$(MAKE) -f CMakeFiles/lib_db.dir/build.make CMakeFiles/lib_db.dir/build
.PHONY : lib_db/fast

#=============================================================================
# Target rules for targets named lib_exception

# Build rule for target.
lib_exception: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_exception
.PHONY : lib_exception

# fast build rule for target.
lib_exception/fast:
	$(MAKE) -f CMakeFiles/lib_exception.dir/build.make CMakeFiles/lib_exception.dir/build
.PHONY : lib_exception/fast

#=============================================================================
# Target rules for targets named lib_file_integrity

# Build rule for target.
lib_file_integrity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_file_integrity
.PHONY : lib_file_integrity

# fast build rule for target.
lib_file_integrity/fast:
	$(MAKE) -f CMakeFiles/lib_file_integrity.dir/build.make CMakeFiles/lib_file_integrity.dir/build
.PHONY : lib_file_integrity/fast

#=============================================================================
# Target rules for targets named lib_logger

# Build rule for target.
lib_logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_logger
.PHONY : lib_logger

# fast build rule for target.
lib_logger/fast:
	$(MAKE) -f CMakeFiles/lib_logger.dir/build.make CMakeFiles/lib_logger.dir/build
.PHONY : lib_logger/fast

#=============================================================================
# Target rules for targets named lib_mysql

# Build rule for target.
lib_mysql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_mysql
.PHONY : lib_mysql

# fast build rule for target.
lib_mysql/fast:
	$(MAKE) -f CMakeFiles/lib_mysql.dir/build.make CMakeFiles/lib_mysql.dir/build
.PHONY : lib_mysql/fast

#=============================================================================
# Target rules for targets named lib_server

# Build rule for target.
lib_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_server
.PHONY : lib_server

# fast build rule for target.
lib_server/fast:
	$(MAKE) -f CMakeFiles/lib_server.dir/build.make CMakeFiles/lib_server.dir/build
.PHONY : lib_server/fast

BerkeleyDB.o: BerkeleyDB.cpp.o
.PHONY : BerkeleyDB.o

# target to build an object file
BerkeleyDB.cpp.o:
	$(MAKE) -f CMakeFiles/lib_db.dir/build.make CMakeFiles/lib_db.dir/BerkeleyDB.cpp.o
.PHONY : BerkeleyDB.cpp.o

BerkeleyDB.i: BerkeleyDB.cpp.i
.PHONY : BerkeleyDB.i

# target to preprocess a source file
BerkeleyDB.cpp.i:
	$(MAKE) -f CMakeFiles/lib_db.dir/build.make CMakeFiles/lib_db.dir/BerkeleyDB.cpp.i
.PHONY : BerkeleyDB.cpp.i

BerkeleyDB.s: BerkeleyDB.cpp.s
.PHONY : BerkeleyDB.s

# target to generate assembly for a file
BerkeleyDB.cpp.s:
	$(MAKE) -f CMakeFiles/lib_db.dir/build.make CMakeFiles/lib_db.dir/BerkeleyDB.cpp.s
.PHONY : BerkeleyDB.cpp.s

client.o: client.cpp.o
.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/fi-client.dir/build.make CMakeFiles/fi-client.dir/client.cpp.o
	$(MAKE) -f CMakeFiles/lib_client.dir/build.make CMakeFiles/lib_client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i
.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/fi-client.dir/build.make CMakeFiles/fi-client.dir/client.cpp.i
	$(MAKE) -f CMakeFiles/lib_client.dir/build.make CMakeFiles/lib_client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s
.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/fi-client.dir/build.make CMakeFiles/fi-client.dir/client.cpp.s
	$(MAKE) -f CMakeFiles/lib_client.dir/build.make CMakeFiles/lib_client.dir/client.cpp.s
.PHONY : client.cpp.s

daemon.o: daemon.cpp.o
.PHONY : daemon.o

# target to build an object file
daemon.cpp.o:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/daemon.cpp.o
	$(MAKE) -f CMakeFiles/lib_daemon.dir/build.make CMakeFiles/lib_daemon.dir/daemon.cpp.o
.PHONY : daemon.cpp.o

daemon.i: daemon.cpp.i
.PHONY : daemon.i

# target to preprocess a source file
daemon.cpp.i:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/daemon.cpp.i
	$(MAKE) -f CMakeFiles/lib_daemon.dir/build.make CMakeFiles/lib_daemon.dir/daemon.cpp.i
.PHONY : daemon.cpp.i

daemon.s: daemon.cpp.s
.PHONY : daemon.s

# target to generate assembly for a file
daemon.cpp.s:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/daemon.cpp.s
	$(MAKE) -f CMakeFiles/lib_daemon.dir/build.make CMakeFiles/lib_daemon.dir/daemon.cpp.s
.PHONY : daemon.cpp.s

exception.o: exception.cpp.o
.PHONY : exception.o

# target to build an object file
exception.cpp.o:
	$(MAKE) -f CMakeFiles/lib_exception.dir/build.make CMakeFiles/lib_exception.dir/exception.cpp.o
.PHONY : exception.cpp.o

exception.i: exception.cpp.i
.PHONY : exception.i

# target to preprocess a source file
exception.cpp.i:
	$(MAKE) -f CMakeFiles/lib_exception.dir/build.make CMakeFiles/lib_exception.dir/exception.cpp.i
.PHONY : exception.cpp.i

exception.s: exception.cpp.s
.PHONY : exception.s

# target to generate assembly for a file
exception.cpp.s:
	$(MAKE) -f CMakeFiles/lib_exception.dir/build.make CMakeFiles/lib_exception.dir/exception.cpp.s
.PHONY : exception.cpp.s

fi-server.o: fi-server.cpp.o
.PHONY : fi-server.o

# target to build an object file
fi-server.cpp.o:
	$(MAKE) -f CMakeFiles/fi-server.dir/build.make CMakeFiles/fi-server.dir/fi-server.cpp.o
.PHONY : fi-server.cpp.o

fi-server.i: fi-server.cpp.i
.PHONY : fi-server.i

# target to preprocess a source file
fi-server.cpp.i:
	$(MAKE) -f CMakeFiles/fi-server.dir/build.make CMakeFiles/fi-server.dir/fi-server.cpp.i
.PHONY : fi-server.cpp.i

fi-server.s: fi-server.cpp.s
.PHONY : fi-server.s

# target to generate assembly for a file
fi-server.cpp.s:
	$(MAKE) -f CMakeFiles/fi-server.dir/build.make CMakeFiles/fi-server.dir/fi-server.cpp.s
.PHONY : fi-server.cpp.s

file-integrity.o: file-integrity.cpp.o
.PHONY : file-integrity.o

# target to build an object file
file-integrity.cpp.o:
	$(MAKE) -f CMakeFiles/lib_file_integrity.dir/build.make CMakeFiles/lib_file_integrity.dir/file-integrity.cpp.o
.PHONY : file-integrity.cpp.o

file-integrity.i: file-integrity.cpp.i
.PHONY : file-integrity.i

# target to preprocess a source file
file-integrity.cpp.i:
	$(MAKE) -f CMakeFiles/lib_file_integrity.dir/build.make CMakeFiles/lib_file_integrity.dir/file-integrity.cpp.i
.PHONY : file-integrity.cpp.i

file-integrity.s: file-integrity.cpp.s
.PHONY : file-integrity.s

# target to generate assembly for a file
file-integrity.cpp.s:
	$(MAKE) -f CMakeFiles/lib_file_integrity.dir/build.make CMakeFiles/lib_file_integrity.dir/file-integrity.cpp.s
.PHONY : file-integrity.cpp.s

logger.o: logger.cpp.o
.PHONY : logger.o

# target to build an object file
logger.cpp.o:
	$(MAKE) -f CMakeFiles/lib_logger.dir/build.make CMakeFiles/lib_logger.dir/logger.cpp.o
.PHONY : logger.cpp.o

logger.i: logger.cpp.i
.PHONY : logger.i

# target to preprocess a source file
logger.cpp.i:
	$(MAKE) -f CMakeFiles/lib_logger.dir/build.make CMakeFiles/lib_logger.dir/logger.cpp.i
.PHONY : logger.cpp.i

logger.s: logger.cpp.s
.PHONY : logger.s

# target to generate assembly for a file
logger.cpp.s:
	$(MAKE) -f CMakeFiles/lib_logger.dir/build.make CMakeFiles/lib_logger.dir/logger.cpp.s
.PHONY : logger.cpp.s

mysql.o: mysql.cpp.o
.PHONY : mysql.o

# target to build an object file
mysql.cpp.o:
	$(MAKE) -f CMakeFiles/lib_mysql.dir/build.make CMakeFiles/lib_mysql.dir/mysql.cpp.o
.PHONY : mysql.cpp.o

mysql.i: mysql.cpp.i
.PHONY : mysql.i

# target to preprocess a source file
mysql.cpp.i:
	$(MAKE) -f CMakeFiles/lib_mysql.dir/build.make CMakeFiles/lib_mysql.dir/mysql.cpp.i
.PHONY : mysql.cpp.i

mysql.s: mysql.cpp.s
.PHONY : mysql.s

# target to generate assembly for a file
mysql.cpp.s:
	$(MAKE) -f CMakeFiles/lib_mysql.dir/build.make CMakeFiles/lib_mysql.dir/mysql.cpp.s
.PHONY : mysql.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/lib_server.dir/build.make CMakeFiles/lib_server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/lib_server.dir/build.make CMakeFiles/lib_server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/lib_server.dir/build.make CMakeFiles/lib_server.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... daemon"
	@echo "... edit_cache"
	@echo "... fi-client"
	@echo "... fi-server"
	@echo "... lib_client"
	@echo "... lib_daemon"
	@echo "... lib_db"
	@echo "... lib_exception"
	@echo "... lib_file_integrity"
	@echo "... lib_logger"
	@echo "... lib_mysql"
	@echo "... lib_server"
	@echo "... rebuild_cache"
	@echo "... BerkeleyDB.o"
	@echo "... BerkeleyDB.i"
	@echo "... BerkeleyDB.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... daemon.o"
	@echo "... daemon.i"
	@echo "... daemon.s"
	@echo "... exception.o"
	@echo "... exception.i"
	@echo "... exception.s"
	@echo "... fi-server.o"
	@echo "... fi-server.i"
	@echo "... fi-server.s"
	@echo "... file-integrity.o"
	@echo "... file-integrity.i"
	@echo "... file-integrity.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... mysql.o"
	@echo "... mysql.i"
	@echo "... mysql.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

